seed: 42

data:
  name: SyntheticPUMatCut32Test
  image_size: 32
  color_channels: 1
  num_workers: 1
  scale_k: 10
  method: kdf
  k_min: 0
  k_max: 10

diffusion:
  name: KdfDDPMDiffusion
  timesteps: 1000
  num_train_timesteps: 1000
  num_infer_timesteps: 1000
  use_custom_model: false
  on_conditioning: true
  conditioning_channels: 2
  use_controlnet: false
#  use_cross_attention: false


model:
  name: UNet
  sample_size: 32
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  block_out_channels: [64, 128, 256, 512]


controlnet_model:
  name: ControlNet
  in_channels: 1
  conditioning_channels: 1
  layers_per_block: 2
  block_out_channels: [64, 128, 256, 512]


training:
  device: cuda
  brand_new_epochs: 1001
  continue_training_epochs: 1001
  batch_size: 64
  use_all_data: false
  amp: true
  log_freq: 1
  snapshot_freq: 1
  eval_freq: 1
  snapshot_sampling: false
  snapshot_batch_size: 2

sampling:
  device: cuda
  batch_size: 1
  eval: true
  total_samples: 4
  record_freq: 1
  eps: 1e-5

optim:
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.1
  beta1: 0.9
  eps: 1e-8
  warmup: 2
  grad_clip: 1.0
  momentum: 0.9

loss_type:
  name: PHY
  lam_phys: 0.5

iio:
  use_tensorboard: true
  use_wandb: false
  save_pth_to_wandb: false

metrics:
  l1: true
  rmse: true
  wrap_l1: true
  wrap_rmse: true
