seed: 42

data:
  name: SyntheticPUMat128Big
  image_size: 128
  color_channels: 1
  num_workers: 1
  k_max: 3
  k_min: 0

mmodel:
  name: PuUNetMModel

model:
  name: PuUNet
  sample_size: 32
  latent_channels: 4
  in_channels: 1
  out_channels: 1
  block_out_channels: [ 32, 64, 128, 32]
#  block_out_channels: [ 32, 64 ]
#  block_out_channels: [ 32,]

training:
  device: cuda
  brand_new_epochs: 1001
  continue_training_epochs: 10001
  batch_size: 128
  use_all_data: false
  amp: true
  log_freq: 1
  snapshot_freq: 10
  eval_freq: 1
  snapshot_sampling: false
  snapshot_batch_size: 2

sampling:
  device: cuda
  batch_size: 8
  eval: true
  total_samples: 8
  record_freq: 1
  eps: 1e-5
  fix_seed: true

val:
  device: cuda
  batch_size: 8
  total_samples: 8
  eps: 1e-5
  fix_seed: true

test:
  device: cuda
  batch_size: 8
  total_samples: 8
  eps: 1e-5
  fix_seed: true

optim:
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0001
  beta1: 0.9
  eps: 1e-8
  warmup: 2
  grad_clip: 1.0
  momentum: 0.9

loss_type:
  name: UNetLOSS

iio:
  use_tensorboard: true
  use_wandb: false
  save_pth_to_wandb: false

metrics:
  l1: true
