# Configuration for training and sampling
seed: 42

data:
  name: InSARDLPUMat
  image_size: 256
  color_channels: 1
  num_workers: 1
#  random_flip: false
#  centered: false
#  uniform_dequantization: false
#  is_fold: true
#  fold: 0
#  num_folds: 5

model:
  name: UNet
  sample_size: 256
  in_channels: 1
  out_channels: 1
  layers_per_block: 2
  block_out_channels: [64, 128, 256, 512]

controlnet_model:
  name: ControlNet
  in_channels: 1
  conditioning_channels: 1
  layers_per_block: 2
  block_out_channels: [64, 128, 256, 512]

diffusion:
  name: DDPMDiffusion
  custom_model: false
  timesteps: 1000
  num_train_timesteps: 1000
  num_infer_timesteps: 50
  beta_start: 0.0001
  beta_end: 0.02
  loss_type: mse

training:
  batch_size: 1
  device: cuda
  brand_new_epochs: 200
  continue_training_epochs: 100
  use_all_data: false
  snapshot_freq: 1
  snapshot_batch_size: 2
  log_freq: 1
  eval_freq: 1
  eval_save_least_epoch: 50
  snapshot_sampling: true
  amp: true

sampling:
  device: cuda
  batch_size: 1
  eval: true
  total_samples: 4
  record_freq: 1
  eps: 1e-5
#  out_threshold: 0.5

optim:
  optimizer: AdamW8bit
  lr: 0.0001
  weight_decay: 0
  beta1: 0.9
  eps: 1e-8
  warmup: 2
  grad_clip: 1.0
  momentum: 0.9

loss_type:
  name: PHY
  lam_phys: 0.5

iio:
  use_tensorboard: true
  use_wandb: false
  save_pth_to_wandb: false

scheduler:
  num_train_timesteps: 50

metrics:
  l1: true
  rmse: true
  wrap_l1: false
  wrap_rmse: false